program: .\sweep_adaboost.py
name: config_adaboost
description: This sweep tests the RGB features together with the HOG features
  on the reduced dataset with JPG images.
method: grid
metric:
  name: accuracy
  goal: maximize
parameters:
  n_bin_x:
    values: [32, 64, 128]
  n_bin_y:
    values: [64, 128, 256]
  cross:
    values: ['none', 'thin', 'fat']
  hsv:
    values: ['True', 'False']
  only_hog:
    values: ['False']
  hog_type:
    values: ['image', 'channels']
  pixels_per_cell:
    values: ['None', [8,8], [16,16], [32,32]]
  max_depth:
    values: [1, 2, 3]
  min_samples_split:
    values: [2, 5, 10]
  min_samples_leaf:
    values: [1, 2, 4]
  n_estimators:
    values: [50, 100, 200]
  learning_rate:
    values: [0.01, 0.1, 1.0]